# roles/startup/task/install_apt.yml

---

- name: roles/startup - Installer les dépendances APT de base
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop: '{{ base_cli_deps }}'
  become: true

- name: Créer un dossier pour bat
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.local/bin"  # Chemin dynamique vers le dossier de l'utilisateur
    state: directory
    mode: '0755'  # Permissions pour exécution

- name: Ajouter un lien symbolique pour bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "/home/{{ ansible_user_id }}/.local/bin/bat"  # Lien symbolique vers bat
    state: link

- name: Détecter les capteurs - lm-sensors
  ansible.builtin.shell: |
    yes | sudo sensors-detect
  changed_when: true
  become: true

- name: Activer le service avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: true
  become: true  # Utilisation des privilèges sudo

- name: Activer le service acpid
  ansible.builtin.systemd:
    name: acpid
    enabled: true
  become: true  # Utilisation des privilèges sudo

- name: Activer le service bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
  become: true  # Utilisation des privilèges sudo

- name: Activer le service lightdm
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
  become: true  # Utilisation des privilèges sudo

- name: Copier les fichiers de configurations 
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_profile/bashrc', dest: '{{ ansible_env.HOME }}/.bashrc'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_profile/vimrc', dest: '{{ ansible_env.HOME }}/.vimrc'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_profile/zshrc', dest: '{{ ansible_env.HOME }}/.zshrc'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/dunst', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/rofi', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/backgrounds', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/terminator', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/picom', dest: '{{ ansible_env.HOME }}/.config'}