# roles/startup/task/main.yml

---

- name: Ajouter le dépôt contrib non-free-firmware
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ CODENAME }} contrib non-free-firmware"
    state: present
  become: true

- name: Ajouter le dépôt contrib non-free
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ CODENAME }} contrib non-free"
    state: present
  become: true

- name: roles/startup - Mettre à jour la liste des paquets
  ansible.builtin.apt:
    update_cache: yes  # Met à jour le cache des paquets
    cache_valid_time: 3600
  become: true

- name: roles/startup - Mettre à niveau les paquets installés
  ansible.builtin.apt:
    upgrade: dist  # Met à niveau tous les paquets installés
  become: true


- include_tasks: install_apt.yml
- include_tasks: install_snap.yml
- include_tasks: install_pipx.yml





