# roles/startup/task/main.yml

---

- name: roles/startup - Ajouter le dépôt contrib non-free-firmware
  ansible.builtin.command: echo | sudo apt-add-repository contrib non-free-firmware
  args:
    warn: false  # Ignore les avertissements si le dépôt existe déjà
  become: true

- name: roles/startup - Mettre à jour la liste des paquets
  ansible.builtin.apt:
    update_cache: yes  # Met à jour le cache des paquets
  become: true

- name: roles/startup - Mettre à niveau les paquets installés
  ansible.builtin.apt:
    upgrade: dist  # Met à niveau tous les paquets installés
  become: true

- name: roles/startup - Installer les dépendances APT de base
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop: '{{ base_cli_deps }}'
  become: true

- name: roles/startup - Installer le paquet Snap core
  ansible.builtin.snap:
    name: "{{ item }}"
    state: present
  loop: '{{ base_cli_snaps }}'
  become: true

- name: roles/startup - Configurer le refresh schedule pour le paquet Snap "core"
  ansible.builtin.command: sudo snap set core refresh.schedule=02:00-04:00
  args:
    warn: false  # Ignore les avertissements sur l'utilisation de sudo dans la commande
  become: true

- name: roles/startup - Installer les dépendances PIPX de base
  community.general.pipx:
    name: '{{ item }}'
  loop: '{{ base_cli_pipx }}'
  environment:
    PIPX_BIN_DIR: "{{ ansible_env.HOME }}/.local/bin"











