# roles/parameter/task/main.yml

# https://github.com/EliverLara/Sweet
# https://github.com/EliverLara/sweet-vscode
# https://github.com/EliverLara/sweet-vscode-icons
# https://github.com/EliverLara/hyper-sweet
# https://github.com/EliverLara/Shades-of-purple-gtk
# https://github.com/ahmadawais/shades-of-purple-vscode
# https://github.com/ahmadawais/shades-of-purple-alacritty
# https://github.com/ahmadawais/shades-of-purple-konsole
# https://github.com/ahmadawais/shades-of-purple-hyper

---

# Installation du themes
- name: Installation des thémes GTK
  block:

    - name: Créer le répertoire des thèmes s'il n'existe pas
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/themes"
        state: directory
        mode: '0755'

    - name: Télécharger le thème Sweet Dark depuis GitHub
      ansible.builtin.get_url:
        url: "{{ THEMES_REPO_SWEET }}"
        dest: "/tmp/swit-dark.zip"

    - name: Extraire le thème
      ansible.builtin.unarchive:
        src: "/tmp/swit-dark.zip"
        dest: "{{ ansible_env.HOME }}/.local/share/themes"
        remote_src: yes

    - name: Télécharger le thème Shades depuis GitHub
      ansible.builtin.get_url:
        url: "{{ THEMES_REPO_SHADES }}"
        dest: "/tmp/Shades_of_purple_gtk.zip"

    - name: Extraire le thème
      ansible.builtin.unarchive:
        src: "/tmp/Shades_of_purple_gtk.zip"
        dest: "{{ ansible_env.HOME }}/.local/share/themes"
        remote_src: yes


# Installation des fonts
# https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#configuration
- name: Installer les fonts
  block:

    - name: Créer le répertoire des fonts s'il n'existe pas
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Copier les fonts Meslo
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/fonts/MesloLGS NF Bold Italic.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/fonts/MesloLGS NF Bold.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/fonts/MesloLGS NF Italic.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/fonts/MesloLGS NF Regular.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}

    - name: Mettre à jour le cache des polices
      ansible.builtin.command:
        cmd: fc-cache -fv
      become: true

# Installation des icons
- name: Installer les icons
  block:

    - name: Créer le répertoire des icons s'il n'existe pas
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/icons/"
        state: directory
        mode: '0755'

    - name: Télécharger les icons Sweet Icon depuis GitHub
      ansible.builtin.get_url:
        url: "{{ ICONS_REPO_SWEET }}"
        dest: "/tmp/Sweet-folders.zip"
        update: yes  # Met à jour le dépôt s'il existe déjà

    - name: Extraire le thème icon Sweet
      ansible.builtin.unarchive:
        src: "/tmp/Sweet-folders.zip"
        dest: "{{ ansible_env.HOME }}/.local/share/icons/"
        remote_src: yes


    - name: Télécharger les icons Candy Icon depuis GitHub
      ansible.builtin.git:
        repo: "{{ ICONS_REPO_CANDY }}"
        dest: "/tmp/candy-icons.zip"
        update: yes  # Met à jour le dépôt s'il existe déjà

    - name: Extraire le thème icon Candy
      ansible.builtin.unarchive:
        src: "/tmp/candy-icons.zip"
        dest: "{{ ansible_env.HOME }}/.local/share/icons/"
        remote_src: yes


- name: Finalisation de l'installation
  become: true
  block:

    - name: Copier les scripts vers le répertoire personnel 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/scripts', dest: '{{ ansible_env.HOME }}'}

    - name: Rendre tous les scripts exécutables
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0755'  # Définit les permissions pour rendre le fichier exécutable
      with_fileglob:
        - "{{ ansible_env.HOME }}/scripts/*.sh"  # Remplacez par le chemin de votre dossier
      

    - name: Copier les configurations 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/profile/bashrc', dest: '{{ ansible_env.HOME }}/.bashrc'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/dunst', dest: '{{ ansible_env.HOME }}/.config'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/rofi', dest: '{{ ansible_env.HOME }}/.config'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/backgrounds', dest: '{{ ansible_env.HOME }}/.config'}
      

    - name: Supprimer les paquets inutilisés
      ansible.builtin.apt:
        autoremove: yes

  

