# roles/parameter/task/main.yml

---

# Installation du themes
- name: Installation des thémes GTK
  block:

    - name: Créer le répertoire des thèmes s'il n'existe pas
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/themes"
        state: directory
        mode: '0755'

    - name: Copier les themes 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/themes/Shades-of-purple', dest: '{{ ansible_env.HOME }}/.local/share/themes'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/themes/Sweet-Dark', dest: '{{ ansible_env.HOME }}/.local/share/themes'}



# Installation des fonts
# https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#configuration
- name: Installer les fonts
  block:

    - name: Créer le répertoire des fonts s'il n'existe pas
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Copier les fonts Meslo
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/fonts/MesloLGS NF Bold Italic.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/fonts/MesloLGS NF Bold.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/fonts/MesloLGS NF Italic.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/fonts/MesloLGS NF Regular.ttf', dest: '{{ ansible_env.HOME }}/.local/share/fonts'}

    - name: Mettre à jour le cache des polices
      ansible.builtin.command:
        cmd: fc-cache -fv
      become: true

# Installation des icons
- name: Installer les icons
  block:

    - name: Créer le répertoire des icons s'il n'existe pas
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/icons/"
        state: directory
        mode: '0755'

    - name: Copier les icons
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/icons/candy-icons', dest: '{{ ansible_env.HOME }}/.local/share/icons'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/icons/Sweet-Purple', dest: '{{ ansible_env.HOME }}/.local/share/icons'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/icons/Sweet-Purple-Filled', dest: '{{ ansible_env.HOME }}/.local/share/icons'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/icons/Sweet-Rainbow', dest: '{{ ansible_env.HOME }}/.local/share/icons'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/icons/Sweet-Red', dest: '{{ ansible_env.HOME }}/.local/share/icons'}
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_local/icons/Sweet-Red-Filled', dest: '{{ ansible_env.HOME }}/.local/share/icons'}


- name: Finalisation de l'installation
  become: true
  block:

    - name: Copier les scripts vers le répertoire personnel 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: '{{ SOURCE_DIR }}/misc/dotfiles/scripts', dest: '{{ ansible_env.HOME }}'}

    - name: Rendre tous les scripts exécutables
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0755'  # Définit les permissions pour rendre le fichier exécutable
      with_fileglob:
        - "{{ ansible_env.HOME }}/scripts/*.sh"  # Remplacez par le chemin de votre dossier
      

    - name: Supprimer les paquets inutilisés
      ansible.builtin.apt:
        autoremove: yes

  

