# roles/software/tasks/install_bravebrowser.yml

---

- name: Télécharger et ajouter la clé GPG de Brave
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    state: present
    keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: true  # Utilisation des privilèges sudo

- name: Ajouter le dépôt Brave Browser
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: 'brave-browser-release.list'
  become: true  # Utilisation des privilèges sudo

- name: Mettre à jour les listes de paquets
  ansible.builtin.apt:
    update_cache: yes
  become: true  # Utilisation des privilèges sudo

- name: Installer Brave Browser
  ansible.builtin.apt:
    name: brave-browser
    state: present
  become: true  # Utilisation des privilèges sudo
