---

# roles/gui/obsidian/task/main.yml

- name: Vérifier si Obsidian est déjà installé
  ansible.builtin.stat:
    path: /usr/bin/obsidian
  register: obsidian_installed
  become: true

- name: Trouver la dernière version d'Obsidian
  ansible.builtin.uri:
    url: '{{ obsidian_url }}'
    return_content: true
  register: obsidian_release
  when: not obsidian_installed.stat.exists
  become: true

- name: Définir le nom du fichier et l'adresse de téléchargement
  set_fact:
    filename: '{{ asset_file.name }}'
    download_url: '{{ asset_file.browser_download_url }}'
  vars:
    asset_file: "{{ obsidian_release.json.assets | selectattr('name', 'contains', 'amd64.deb') | join() }}"
  when: not obsidian_installed.stat.exists
  become: true

- name: Télécharger Obsidian
  ansible.builtin.get_url:
    url: '{{ download_url }}'
    dest: '{{ build_dir }}/obsidian/obsidian-setup.deb'
  when: not obsidian_installed.stat.exists
  become: true

- name: Installer Obsidian
  ansible.builtin.apt:
    deb: '{{ build_dir }}/obsidian/obsidian-setup.deb'
    state: present
  when: not obsidian_installed.stat.exists
  become: true