---

# Fichier principal main.yml

- name: '{{ PROJECT }} - {{ CODENAME }}'
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - role: 'roles/startup'
      tags: 'startup'
    - role: 'roles/environnement'
      tags: 'environnement'
    - role: 'roles/software'
      tags: 'software'
    # - role: 'roles/dev'
    #   tags: 'dev'
    # - role: 'roles/pentest'
    #   tags: 'pentest'
    # - role: 'roles/parameter'
    #   tags: 'parameter'
      users:
        - username: '{{ ansible_user_id }}'