# roles/cleanup/task/main.yml

---


- name: Copier les scripts vers le répertoire personnel 
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/scripts', dest: '{{ ansible_env.HOME }}'}
  become: true  # Utilisation des privilèges sudo


- name: Rendre tous les scripts exécutables
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'  # Définit les permissions pour rendre le fichier exécutable
  with_fileglob:
    - "{{ ansible_env.HOME }}/scripts/*.sh"  # Remplacez par le chemin de votre dossier
  become: true
  

- name: Copier les configurations 
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/profile/bashrc', dest: '{{ ansible_env.HOME }}/.bashrc'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/dunst', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/rofi', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/backgrounds', dest: '{{ ansible_env.HOME }}/.config'}
  become: true  # Utilisation des privilèges sudo
  

- name: Supprimer les paquets inutilisés
  ansible.builtin.apt:
    autoremove: yes
  become: true  # Utilisation des privilèges sudo

  

