# roles/cleanup/task/main.yml

---

- name: Mettre à jour les répertoires utilisateur
  ansible.builtin.command: xdg-user-dirs-update
  become: true  # Utilisation des privilèges sudo


- name: Supprimer les paquets inutilisés
  ansible.builtin.apt:
    autoremove: yes
  become: true  # Utilisation des privilèges sudo


- name: Copier les scripts vers le répertoire personnel 
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/scripts', dest: '{{ ansible_env.HOME }}'}
  become: true  # Utilisation des privilèges sudo

- name: Rendre les scripts exécutables
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
  loop:
    - '{{ ansible_env.HOME }}/scripts/*.sh'
  become: true  # Utilisation des privilèges sudo


- name: Rendre tous les scripts d'un dossier exécutables
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'  # Définit les permissions pour rendre le fichier exécutable
  with_fileglob:
    - "{{ ansible_env.HOME }}/scripts/*.sh"  # Remplacez par le chemin de votre dossier
  become: true



  
- name: Copier les fichiers de configuration de Mozilla
  ansible.builtin.copy:
    src: .mozilla/
    dest: ~/
    remote_src: yes
  become: true  # Utilisation des privilèges sudo

  
- name: Copier les configurations du terminal Konsole
  ansible.builtin.copy:
    src: config/konsole/
    dest: ~/.local/share/
    remote_src: yes
  become: true  # Utilisation des privilèges sudo

- name: Copier le thème Sweet-Dark-v40 vers les thèmes système
  ansible.builtin.copy:
    src: config/Sweet-Dark-v40/
    dest: /usr/share/themes/
    remote_src: yes
  become: true  # Utilisation des privilèges sudo
  

- name: Copier les configurations 
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/profile/bashrc', dest: '{{ ansible_env.HOME }}/.bashrc'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/dunst', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/rofi', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/chromium', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/Brave-Browse', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/terminator', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/konsolerc', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/xfce4', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/gtk-3.0', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/gtk-4.0', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/QtProject.conf', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/copyq', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/galculator', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/kcalcrc', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/backgrounds', dest: '{{ ansible_env.HOME }}/.config'}
    # - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/sublime-text', dest: '$HOME/.config'}
    # - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/Brackets', dest: '$HOME/.config'}
  become: true  # Utilisation des privilèges sudo
  



  

