---

# roles/devops/docker/task/main.yml

- name: Installer docker seulement si /usr/bin/docker n'existe pas
  ansible.builtin.stat:
    path: '/usr/bin/docker'
  register: docker_installed

- name: Installation de docker
  ansible.builtin.shell: |
    cd {{ build_dir }}/docker
    curl -fsSL "https://get.docker.com/" | sh
  become: true
  when: not docker_installed.stat.exists

- name: Ajouter l'utilisateur au groupe Docker
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  when: not docker_installed.stat.exists

- name: Appliquer les changements de groupe dans la session actuelle
  ansible.builtin.shell: |
    newgrp docker || true
  become_user: "{{ ansible_user_id }}"
  ignore_errors: true