# roles/environnement/task/install_vim.yml

---

- name: Installation de vim
  ansible.builtin.apt:
    name: vim
    state: present
  become: true

# - name: S'assurer que le répertoire de destination existe pour vim-plug
#   ansible.builtin.file:
#     path: $HOME/.vim/autoload
#     state: directory

# - name: Installation de vim-plug
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     dest: $HOME/.vim/autoload/plug.vim

# - name: S'assurer que le répertoire de destination existe pour les couleurs de vim
#   ansible.builtin.file:
#     dest: $HOME/.vim/colors
#     state: directory

# - name: Installer le thème de couleurs Snazzy pour vim
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/connorholyday/vim-snazzy/master/colors/snazzy.vim
#     dest: $HOME/.vim/colors

- name: Copier la configuration de vim
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/profile/vimrc', dest: '{{ ansible_env.HOME }}/.vimrc'}

# - name: Installation des pluggins
#   ansible.builtin.shell: vim '+PlugInstall --sync' +qall
