---

# roles/common/mise/task/main.yml

# mise ls -> tool installer sur systeme
# mise ls-remote -> tool disponible a l'installation

- name: Installation de https://mise.jdx.dev
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.local/bin/mise'
  register: mise_installed

- name: Création du répertoire /etc/apt/keyrings pour https://mise.jdx.dev
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: '0755'
  when: not mise_installed.stat.exists

- name: Téléchargement du script d'installation de https://mise.jdx.dev
  ansible.builtin.get_url:
    url: https://mise.jdx.dev/install.sh
    dest: '/tmp/install.sh'
    mode: '0755'

- name: Executer le script d'installation de https://mise.jdx.dev
  ansible.builtin.shell: '/tmp/install.sh'

- name: Installer la liste d'outils avec https://mise.jdx.dev 
  ansible.builtin.shell: >
    bash -c 'mise use -g {{ item.name }} || true'
  loop: "{{ mise_install }}"

# No bash -i as it allows cargo to run jobs in the background in a weird way that breaks ansible
- name: Installer les outils basés sur Cargo
  ansible.builtin.shell: bash -c 'mise exec -- cargo install {{ item.name }}'
  loop: "{{ mise_cargo_install }}"