---

# roles/common/cargo/task/main.yml

# No bash -i as it allows cargo to run jobs in the background in a weird way that breaks ansible
- name: Installer les outils basés sur Cargo
  ansible.builtin.shell: bash -c 'mise exec -- cargo install {{ item.name }}'
  loop: "{{ cargo_install }}"




    