# roles/environnement/taskS/install_asdf.yml

---

# https://asdf-vm.com/guide/getting-started.html

- name: Installer les dépendances requises pour asdf
  ansible.builtin.apt:
    name:
      - dirmngr 
      - gpg 
      - curl 
      - gawk
      - git
    state: present
  become: true

- name: Cloner, mettre à jour et basculer sur la version spécifique du dépôt asdf
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"  
  loop: "{{ ASDF_REPO }}"

- name: Ajouter la configuration asdf dans .bashrc 
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$HOME/.asdf/asdf.sh"'
    state: present

- name: Ajouter la complétion asdf dans .bashrc 
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$HOME/.asdf/completions/asdf.bash"'
    state: present


- name: Recharger le shell .bashrc
  shell: source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash
  ignore_errors: true
  become: true  # Utilisation des privilèges sudo


- name: Installer les plugins asdf
  ansible.builtin.command: asdf plugin-add {{ item.name }}
  loop: "{{ asdf_install }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Installer les versions des paquets asdf
  ansible.builtin.command: asdf install {{ item.name }} latest
  loop: "{{ asdf_install }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Définir la version globale pour chaque paquet
  ansible.builtin.command: asdf global {{ item.name }} latest
  loop: "{{ asdf_install }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"