# roles/environnement/task/main.yml

---

## https://github.com/Airblader/i3/wiki/Building-from-source

- name: Installer les dépendances requises pour i3-gaps
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop: '{{ i3_gaps_dependencies }}'
  become: true

- name: Cloner le dépôt i3-gaps
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes # Clonage ou mise à jour
  loop: "{{ I3GAPS_REPO }}"


- name: Cloner le dépôt bumblebee
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes # Clonage ou mise à jour
  loop: "{{ BUMBLEBEE_REPO }}"


- name: Reconfiguration et compilation avec Meson et Ninja i3-gaps
  ansible.builtin.shell: |
    cd {{ item.dest }} && meson setup build 
    cd {{ item.dest }}/build && ninja && sudo ninja install
  loop: "{{ I3GAPS_REPO }}"
  become: true

- name: Copier la configuration de i3-gaps.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/i3', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/dot_config/i3blocks', dest: '{{ ansible_env.HOME }}/.config'}


- name: Rendre les scripts exécutables
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
  loop:
    - '{{ ansible_env.HOME }}/.config/i3/autostart.sh'
    - '{{ ansible_env.HOME }}/.config/i3blocks/scripts/i3-clock'
    - '{{ ansible_env.HOME }}/.config/i3blocks/scripts/i3-date'
    - '{{ ansible_env.HOME }}/.config/i3blocks/scripts/i3-disk'
    - '{{ ansible_env.HOME }}/.config/i3blocks/scripts/i3-internet'
    - '{{ ansible_env.HOME }}/.config/i3blocks/scripts/i3-nettraf'
    - '{{ ansible_env.HOME }}/.config/i3blocks/scripts/i3-volume'
  become: true  # Utilisation des privilèges sudo


- name: Copier les scripts vers le répertoire personnel 
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/scripts', dest: '{{ ansible_env.HOME }}'}

- name: Rendre tous les scripts exécutables
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'  # Définit les permissions pour rendre le fichier exécutable
  with_fileglob:
    - "{{ ansible_env.HOME }}/scripts/*.sh"  # Remplacez par le chemin de votre dossier


- name: Créer une entrée de session pour i3
  ansible.builtin.copy:
    dest: /usr/share/xsessions/i3.desktop
    content: |
      [Desktop Entry]
      Name=i3
      Comment=Tiling window manager
      Exec=i3
      TryExec=i3
      Type=Application
      X-LightDM-DesktopName=i3
      DesktopNames=i3
      Keywords=tiling;wm;windowmanager;
      StartupNotify=false
    mode: '0644'
  become: true  # Utilisation des privilèges sudo