# roles/environnement/task/main.yml

---

# https://github.com/polybar/polybar/wiki/Compiling
# https://github.com/the-anonymous-raven/polybar-themes/tree/main
# https://github.com/jbirnick/polybar-timer

- name: Installer les dépendances requises pour polybar
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop: '{{ polybar_dependencies }}'
  become: true

- name: Installer les dépendances optionnel pour polybar
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop: '{{ polybar_dependencies_optional }}'
  become: true

- name: Cloner, mettre à jour et basculer sur la version spécifique du dépôt polybar
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    # version: "{{ item.app_version }}"  # Branche, tag ou commit spécifique
    update: yes # Clonage ou mise à jour
  loop: "{{ POLYBAR_REPO }}"
  # Commande Git associée :
  # git clone {{ item.repo }} {{ item.dest }} --branch {{ item.app_version }} --single-branch
  # git pull origin {{ item.app_version }}  # Effectué automatiquement si `dest` existe déjà

- name: Compilation du repo de polybar
  ansible.builtin.shell: |
    mkdir -p build && cd build
    cmake .. && make -j$(nproc) && sudo make install
  args:
    chdir: '{{ BUILD_DIR }}/polybar'
  become: true

- name: S'assurer que le répertoire de configuration pour polybar existe.
  ansible.builtin.file:
    path: $HOME/.config/polybar
    state: directory

- name: S'assurer que le répertoire des scripts pour polybar existe.
  ansible.builtin.file:
    path: $HOME/.config/polybar/scripts
    state: directory

- name: Copier la configuration de polybar.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/polybar/config', dest: '$HOME/.config/polybar'}
 

- name: Copier les scripts de polybar.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/polybar/launch.sh', dest: '$HOME/.config/polybar'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/polybar/scripts/dmenu.sh', dest: '$HOME/.config/polybar/scripts'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/polybar/scripts/polywins.sh', dest: '$HOME/.config/polybar/scripts'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/polybar/scripts/polybar-timer.sh', dest: '$HOME/.config/polybar/scripts'}

