- name: Installer l'antivirus ClamAV
  become: true
  block:
    # Paramètres de ClamAV uniquement pour le PC hôte, analyse automatique, mais nécessite au moins 1 Go de RAM (les bases de données sont toujours en RAM)
    # La VM peut analyser le système avec ClamTK manuellement

    - name: Installer ClamAV 
      ansible.builtin.apt:
        name: clamav-daemon
        state: present
        update_cache: yes

    - name: Activer le service clamav-daemon qui charge les définitions de base de données de virus en mémoire et gère l'analyse des fichiers
      ansible.builtin.systemd:
        name: clamav-daemon
        enabled: true
        state: started

    - name: Créer des dossiers pour la quarantaine
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items:
        - /root/.clamav/quarantine
        - /root/.clamav/logs

    - name: Créer une nouvelle tâche cron pour analyser le système tous les 20 jours du mois à 21h00
      ansible.builtin.cron:
        name: "Analyse du système ClamAV"
        minute: "0"
        hour: "21"
        day: "20"
        month: "*"
        weekday: "0"
        user: "root"
        job: "/usr/bin/clamdscan --fdpass --log=/root/.clamav/logs/scan-$(date +'%d-%m-%Y-%T').log --move=/root/.clamav/quarantine /"

    - name: Ajouter des chemins à exclure dans le fichier de configuration de clamav
      ansible.builtin.blockinfile:
        path: /etc/clamav/clamd.conf
        block: |
          # Exclure de l'analyse
          ExcludePath ^/proc
          ExcludePath ^/sys
          ExcludePath ^/run
          ExcludePath ^/dev
          ExcludePath ^/var/lib/lxcfs/cgroup
          ExcludePath ^/root/clamav/quarantine

    - name: Redémarrer le service clamav-daemon après les modifications dans le fichier de configuration
      ansible.builtin.systemd:
        name: clamav-daemon
        state: restarted


- name: Installer le pare-feu - nftables
  become: true
  block:

    - name: Installer nftables
      ansible.builtin.apt:
        name: 
          - nftables
          - rsyslog
        state: present
        update_cache: yes

    - name: Activer le service nftables
      ansible.builtin.systemd:
        name: nftables
        enabled: true
        state: started

    - name: Activer le service rsyslog 
      ansible.builtin.systemd:
        name: rsyslog
        enabled: true
        state: started

    - name: Créer une table nftables
      command: nft add table ip filter
      ignore_errors: true  # Ignorer les erreurs si la table existe déjà

    - name: Créer une chaîne pour les connexions entrantes
      command: nft add chain ip filter input { type filter hook input priority 0; }
      ignore_errors: true  # Ignorer les erreurs si la chaîne existe déjà

    - name: Créer une chaîne pour les connexions sortantes
      command: nft add chain ip filter output { type filter hook output priority 0; }
      ignore_errors: true  # Ignorer les erreurs si la chaîne existe déjà

    - name: Définir la politique d'entrée sur le PC hôte à refuser
      command: nft add rule ip filter input reject

    - name: Définir la politique de sortie sur le PC hôte à autoriser
      command: nft add rule ip filter output accept

    - name: Accepter les connexions établies
      command: nft add rule ip filter input ct state established,related accept

    # - name: Accepter les requêtes ICMP
    #   command: nft add rule ip filter input icmp type echo-request accept

    # - name: Accepter les connexions SSH
    #   command: nft add rule ip filter input tcp dport 22 accept

    - name: Journaliser les connexions refusées
      command: nft add rule ip filter input log prefix \"nft drop:\" level debug

    - name: Créer la configuration de rsyslog pour nftables
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/nftables.conf
        content: ":msg, startswith, \"nft drop\" -/var/log/nftables.log\n& stop\n"
        owner: root
        group: root
        mode: '0644'

    - name: Redémarrer le service rsyslog
      ansible.builtin.systemd:
        name: rsyslog
        state: restarted

    - name: Configurer la rotation des journaux pour nftables
      ansible.builtin.copy:
        dest: /etc/logrotate.d/nftables
        content: |
          /var/log/nftables.log {
            size +10M
            maxage 30
            sharedscripts
            postrotate
              /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
            endscript
          }
        owner: root
        group: root
        mode: '0644'

    # Cette configuration vous permettra de suivre facilement les paquets abandonnés 
    # et d'éviter que votre fichier journal ne devienne trop volumineux. 
    # Vous pourrez consulter les logs en temps réel à l'aide de la commande suivante :
    # sudo tail -f /var/log/nftables.log


  when: FIREWALL == 'nftables'