# roles/environnement/taskS/install_asdf.yml

---

# https://asdf-vm.com/guide/getting-started.html

- name: Installer les dépendances requises pour asdf
  ansible.builtin.apt:
    name:
      - dirmngr 
      - gpg 
      - curl 
      - gawk
      - git
    state: present
  become: true

- name: Cloner, mettre à jour et basculer sur la version spécifique du dépôt asdf
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"  
  loop: "{{ ASDF_REPO }}"

- name: Ajouter la configuration asdf dans .bashrc 
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$HOME/.asdf/asdf.sh"'
    state: present

- name: Ajouter la complétion asdf dans .bashrc 
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$HOME/.asdf/completions/asdf.bash"'
    state: present

- name: Installer les plugins asdf pour les langages
  ansible.builtin.shell: . $HOME/.asdf/asdf.sh && asdf plugin-add {{ item.name }}
  loop: "{{ asdf_install_langages }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Installer les versions des langages asdf
  ansible.builtin.shell: . $HOME/.asdf/asdf.sh && asdf install {{ item.name }} latest
  loop: "{{ asdf_install_langages }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Installer les plugins asdf pour les outils/utilitaires
  ansible.builtin.shell: . $HOME/.asdf/asdf.sh && asdf plugin-add {{ item.name }}
  loop: "{{ asdf_install_utilitaires }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Installer les versions des outils/utilitaires asdf
  ansible.builtin.shell: . $HOME/.asdf/asdf.sh && asdf install {{ item.name }} latest
  loop: "{{ asdf_install_utilitaires }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Définir les versions globales des langages asdf
  ansible.builtin.shell: . $HOME/.asdf/asdf.sh && asdf global {{ item.name }} latest
  loop: "{{ asdf_install_langages }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Définir les versions globales des outils/utilitaires asdf
  ansible.builtin.shell: . $HOME/.asdf/asdf.sh && asdf global {{ item.name }} latest
  loop: "{{ asdf_install_utilitaires }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Recharger le shell .bashrc
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash
  ignore_errors: true
