# roles/environnement/taskS/install_asdf.yml

---

# https://asdf-vm.com/guide/getting-started.html

- name: Installer les dépendances requises pour asdf
  ansible.builtin.apt:
    name:
      - dirmngr 
      - gpg 
      - curl 
      - gawk
      - git
    state: present
  become: true

- name: Cloner, mettre à jour et basculer sur la version spécifique du dépôt asdf
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"  
  loop: "{{ ASDF_REPO }}"

- name: Ajouter la configuration asdf dans .bashrc 
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$HOME/.asdf/asdf.sh"'
    state: present

- name: Ajouter la complétion asdf dans .bashrc 
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$HOME/.asdf/completions/asdf.bash"'
    state: present

# Boucle sur langages et utilitaires pour l'installation des plugins, des versions et la définition globale
- name: Gérer les langages et utilitaires asdf (plugin, installation et global)
  ansible.builtin.shell: |
    . $HOME/.asdf/asdf.sh
    asdf plugin-add {{ item.name }} || true
    asdf install {{ item.name }} latest
    asdf global {{ item.name }} latest
  loop: "{{ asdf_packages }}"
  environment:
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"

- name: Recharger le shell .bashrc
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash
  ignore_errors: true
