# roles/environnement/task/main.yml

---

## https://github.com/Airblader/i3/wiki/Building-from-source

- name: Installer les dépendances requises pour i3-gaps
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop: '{{ i3_gaps_dependencies }}'
  become: true

- name: Cloner, mettre à jour et basculer sur la version spécifique du dépôt i3-gaps
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    # version: "{{ item.app_version }}"  # Branche, tag ou commit spécifique
    update: yes # Clonage ou mise à jour
  loop: "{{ I3GAPS_REPO }}"
  # Commande Git associée :
  # git clone {{ item.repo }} {{ item.dest }} --branch {{ item.app_version }} --single-branch
  # git pull origin {{ item.app_version }}  # Effectué automatiquement si `dest` existe déjà


- name: Reconfiguration et compilation avec Meson et Ninja i3-gaps
  ansible.builtin.shell: |
    cd {{ item.dest }} && meson setup build 
    cd {{ item.dest }}/build && ninja && sudo ninja install
  loop: "{{ I3GAPS_REPO }}"
  become: true

- name: Copier la configuration de i3-gaps.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/i3', dest: '{{ ansible_env.HOME }}/.config'}
    - {src: '{{ SOURCE_DIR }}/misc/dotfiles/config/i3blocks', dest: '{{ ansible_env.HOME }}/.config'}
  become: true  # Utilisation des privilèges sudo

- name: Rendre les scripts exécutables
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
  loop:
    - '{{ ansible_env.HOME }}/.config/i3/autostart.sh'
    - '{{ ansible_env.HOME }}/.config/i3blocks/cpu/cpu_info.sh'
    - '{{ ansible_env.HOME }}/.config/i3blocks/battery/battery_info.sh'
    - '{{ ansible_env.HOME }}/.config/i3blocks/weather/weather.sh'
    - '{{ ansible_env.HOME }}/.config/i3blocks/weather/weather.py'
  become: true  # Utilisation des privilèges sudo

- name: Créer une entrée de session pour i3
  ansible.builtin.copy:
    dest: /usr/share/xsessions/i3.desktop
    content: |
      [Desktop Entry]
      Name=i3
      Comment=Tiling window manager
      Exec=i3
      TryExec=i3
      Type=Application
      X-LightDM-DesktopName=i3
      DesktopNames=i3
      Keywords=tiling;wm;windowmanager;
      StartupNotify=false
  mode: '0644'