- name: Installer l'antivirus ClamAV
  become: true
  block:
    # Paramètres de ClamAV uniquement pour le PC hôte, analyse automatique, mais nécessite au moins 1 Go de RAM (les bases de données sont toujours en RAM)
    # La VM peut analyser le système avec ClamTK manuellement

    - name: Installer ClamAV 
      ansible.builtin.apt:
        name: clamav-daemon
        state: present
        update_cache: yes

    - name: Activer le service clamav-daemon qui charge les définitions de base de données de virus en mémoire et gère l'analyse des fichiers
      ansible.builtin.systemd:
        name: clamav-daemon
        enabled: true
        state: started

    - name: Créer des dossiers pour la quarantaine
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items:
        - /root/.clamav/quarantine
        - /root/.clamav/logs

    - name: Créer une nouvelle tâche cron pour analyser le système tous les 20 jours du mois à 21h00
      ansible.builtin.cron:
        name: "Analyse du système ClamAV"
        minute: "0"
        hour: "21"
        day: "20"
        month: "*"
        weekday: "0"
        user: "root"
        job: "/usr/bin/clamdscan --fdpass --log=/root/.clamav/logs/scan-$(date +'%d-%m-%Y-%T').log --move=/root/.clamav/quarantine /"

    - name: Ajouter des chemins à exclure dans le fichier de configuration de clamav
      ansible.builtin.blockinfile:
        path: /etc/clamav/clamd.conf
        block: |
          # Exclure de l'analyse
          ExcludePath ^/proc
          ExcludePath ^/sys
          ExcludePath ^/run
          ExcludePath ^/dev
          ExcludePath ^/var/lib/lxcfs/cgroup
          ExcludePath ^/root/clamav/quarantine

    - name: Redémarrer le service clamav-daemon après les modifications dans le fichier de configuration
      ansible.builtin.systemd:
        name: clamav-daemon
        state: restarted


# https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
- name: Installer le pare-feu - ufw
  become: true
  block:

    - name: Installer ufw 
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Définir la politique d'entrée sur le PC hôte à refuser
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Autoriser les connexions sortantes
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Activer UFW
      community.general.ufw:
        state: enabled

# Les niveaux de journalisation UFW

# UFW propose plusieurs niveaux de journalisation. Chaque niveau ajuste la quantité d'informations collectées :

#     off : Désactive la journalisation.
#     low : Journalise les événements de base, principalement les connexions rejetées ou bloquées.
#     medium : Journalise les connexions rejetées et autorisées, mais de manière succincte.
#     high : Journalise davantage de détails, y compris les informations sur le trafic autorisé.
#     full : Journalise tout, y compris les informations complètes sur les paquets et connexions.

# Où trouver les logs :
# sudo tail -f /var/log/ufw.log

    - name: Activer la journalisation UFW
      community.general.ufw:
        logging: 'on'

    - name: Configurer la journalisation UFW à un niveau élevé
      community.general.ufw:
        logging: 'high'

  when: FIREWALL == 'ufw'


  ##################################""

- name: Installer le pare-feu - nftables
  become: true
  block:

    - name: Installer nftables
      ansible.builtin.apt:
        name: nftables
        state: present
        update_cache: yes

    - name: Activer le service nftables
      ansible.builtin.systemd:
        name: nftables
        enabled: true
        state: started

    - name: Créer une table nftables
      command: nft add table ip filter
      ignore_errors: true  # Ignorer les erreurs si la table existe déjà

    - name: Créer une chaîne pour les connexions entrantes
      command: nft add chain ip filter input { type filter hook input priority 0; }
      ignore_errors: true  # Ignorer les erreurs si la chaîne existe déjà

    - name: Créer une chaîne pour les connexions sortantes
      command: nft add chain ip filter output { type filter hook output priority 0; }
      ignore_errors: true  # Ignorer les erreurs si la chaîne existe déjà

    - name: Définir la politique d'entrée sur le PC hôte à refuser
      command: nft add rule ip filter input reject

    - name: Définir la politique de sortie sur le PC hôte à autoriser
      command: nft add rule ip filter output accept

    - name: Accepter les connexions établies
      command: nft add rule ip filter input ct state established,related accept

    # - name: Accepter les requêtes ICMP
    #   command: nft add rule ip filter input icmp type echo-request accept

    # - name: Accepter les connexions SSH
    #   command: nft add rule ip filter input tcp dport 22 accept

    # Note: nftables ne prend pas en charge la journalisation de la même manière qu'UFW
    # mais vous pouvez activer le logging avec une règle comme suit :
    # sudo tail -f /var/log/syslog | grep "nftables denied"
    # sudo tail -f /var/log/syslog
    # sudo tail -f /var/log/messages
    # sudo journalctl -f

    - name: Journaliser les connexions refusées
      command: nft add rule ip filter input log prefix "nftables denied: " level debug

    - name: Vérifier les règles nftables
      command: nft list ruleset
      register: nft_ruleset

    - name: Afficher les règles nftables
      debug:
        msg: "{{ nft_ruleset.stdout }}"

  when: FIREWALL == 'nftables'