#############################################################################################################
# Virtualization
#############################################################################################################

# Installation de VirtualBox
- name: Installer VirtualBox
  become: true
  block:

    # Télécharger le fichier .deb de VirtualBox 7.0.18
    - name: Télécharger VirtualBox 7.0.18 pour Debian 12
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/7.0.18/virtualbox-7.0_7.0.18-162988~Debian~bookworm_amd64.deb
        dest: /tmp/virtualbox-7.0.18.deb

    # Installer les dépendances nécessaires
    - name: Installer les dépendances
      apt:
        name:
          - dkms
          - linux-headers-{{ ansible_kernel }}
        state: present
        update_cache: yes

    # Installer VirtualBox depuis le fichier .deb
    - name: Installer VirtualBox depuis le fichier .deb
      ansible.builtin.apt:
        deb: /tmp/virtualbox-7.0.18.deb

    # Corriger les dépendances manquantes si nécessaire
    - name: Corriger les dépendances manquantes
      command: apt --fix-broken install -y
      when: ansible_facts.packages.virtualbox is not defined

    # Télécharger l'Extension Pack de VirtualBox 7.0.18
    - name: Télécharger l'Extension Pack de VirtualBox 7.0.18
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/7.0.18/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack
        dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack

    # Installer l'Extension Pack
    - name: Installer l'Extension Pack
      command: VBoxManage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack
      when: ansible_facts.packages.virtualbox is defined

    - name: Enregistrer la liste des réseaux NAT de VirtualBox
      ansible.builtin.shell: VBoxManage natnetwork list
      changed_when: false
      register: virtualbox_natnetwork

    - name: Ajouter un réseau NAT à VirtualBox
      ansible.builtin.shell: VBoxManage natnetwork add --netname NatNetwork --network "10.0.2.0/24" --enable
      changed_when: virtualbox_natnetwork.stdout | regex_search('0 networks found')

    - name: Enregistrer la liste des interfaces host-only de VirtualBox
      ansible.builtin.shell: VBoxManage list hostonlyifs
      changed_when: false
      register: virtualbox_host_only_network

    - name: Ajouter un réseau host-only à VirtualBox
      ansible.builtin.shell: VBoxManage hostonlyif create
      changed_when: virtualbox_host_only_network.stdout | length == 0

# Installation de KVM
- name: Installer KVM
  become: true
  block:
    - name: Installer les dépendances de virtualisation KVM
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - virtinst
          - libvirt-clients
          - bridge-utils
          - virt-manager
        update_cache: yes  # Met à jour le cache des paquets avant l'installation

    - name: Activer et démarrer le service libvirtd
      ansible.builtin.systemd:
        name: libvirtd
        enabled: true
        state: started

    - name: Ajouter l'utilisateur au groupe KVM et Libvirt
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        append: true
        groups:
          - kvm
          - libvirt
